name: deploy-backend
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  deploy-backend:
    name: deploy-backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish Src/InGreed.Api/InGreed.Api.csproj -c Release --nologo -o artifacts --self-contained -r win-x64

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: BackendFiles
        path: /home/runner/work/IO2_InGreed.io-1/IO2_InGreed.io-1/artifacts/
